INSERT OR IGNORE INTO persons (id, name, category, occupation, hints) VALUES
-- Film (30)
('film-spielberg', 'Steven Spielberg', 'film', 'reżyser', '["Reżyser wielu filmów przygodowych.","Stoi za filmem o rekinie z 1975 roku.","Wyreżyserował „Lista Schindlera”."]'),
('film-nolan', 'Christopher Nolan', 'film', 'reżyser', '["Tworzy filmy o nielinearnej narracji.","Wyreżyserował trylogię o Mrocznym Rycerzu.","Jest autorem „Incepcja”."]'),
('film-scorsese', 'Martin Scorsese', 'film', 'reżyser', '["Często opowiada o świecie przestępczym.","Współpracował wielokrotnie z Robertem De Niro.","Wyreżyserował „Chłopcy z ferajny”."]'),
('film-cameron', 'James Cameron', 'film', 'reżyser', '["Twórca widowisk science‑fiction.","Wyreżyserował „Titanic”.","Stoi za „Avatar”."]'),
('film-ridley-scott', 'Ridley Scott', 'film', 'reżyser', '["Twórca filmów science‑fiction i historycznych.","Wyreżyserował „Obcy”.","Stoi za „Gladiator”."]'),
('film-peter-jackson', 'Peter Jackson', 'film', 'reżyser', '["Pochodzi z Nowej Zelandii.","Wyreżyserował trylogię „Władca Pierścieni”.","Zdobył Oscara za „Powrót króla”."]'),
('film-fincher', 'David Fincher', 'film', 'reżyser', '["Znany z mrocznych thrillerów.","Wyreżyserował „Siedem”.","Stoi za „Podziemny krąg”."]'),
('film-villeneuve', 'Denis Villeneuve', 'film', 'reżyser', '["Pochodzi z Kanady.","Wyreżyserował „Blade Runner 2049”.","Stoi za „Diuna”."]'),
('film-tarantino', 'Quentin Tarantino', 'film', 'reżyser', '["Znany z charakterystycznych dialogów.","Wyreżyserował „Pulp Fiction”.","Stoi za serią „Kill Bill”."]'),
('film-kubrick', 'Stanley Kubrick', 'film', 'reżyser', '["Słynął z perfekcjonizmu.","Wyreżyserował „2001: Odyseja kosmiczna”.","Stoi za „Lśnienie”."]'),
('film-leonardo-dicaprio', 'Leonardo DiCaprio', 'film', 'aktor', '["Zagrał w „Titanic”.","Często pracował z Martinem Scorsese.","Zdobył Oscara za „Zjawa”."]'),
('film-meryl-streep', 'Meryl Streep', 'film', 'aktorka', '["Rekordzistka nominacji do Oscara.","Zagrała w „Sophie Choice”.","Wystąpiła w „Diabeł ubiera się u Prady”."]'),
('film-tom-hanks', 'Tom Hanks', 'film', 'aktor', '["Zagrał w „Forrest Gump”.","Wystąpił w „Szeregowiec Ryan”.","Znany z filmu „Cast Away”."]'),
('film-natalie-portman', 'Natalie Portman', 'film', 'aktorka', '["Zdobyła Oscara za „Czarny łabędź”.","Zagrała w „Leon Zawodowiec”.","Wystąpiła w prequelach „Gwiezdne wojny”."]'),
('film-denzel-washington', 'Denzel Washington', 'film', 'aktor', '["Dwukrotny zdobywca Oscara.","Zagrał w „Training Day”.","Wystąpił w „Malcolm X”."]'),
('film-brad-pitt', 'Brad Pitt', 'film', 'aktor', '["Zagrał w „Fight Club”.","Wystąpił w „Siedem”.","Zdobył Oscara za „Pewnego razu... w Hollywood”."]'),
('film-cate-blanchett', 'Cate Blanchett', 'film', 'aktorka', '["Zagrała Galadrielę we „Władcy Pierścieni”.","Zdobyła Oscara za „Blue Jasmine”.","Wystąpiła w „Elizabeth”."]'),
('film-morgan-freeman', 'Morgan Freeman', 'film', 'aktor', '["Znany z charakterystycznego głosu.","Zagrał w „Skazani na Shawshank”.","Wystąpił jako mentor Batmana."]'),
('film-scarlett-johansson', 'Scarlett Johansson', 'film', 'aktorka', '["Zagrała Czarną Wdowę w MCU.","Wystąpiła w „Her”.","Znana z filmu „Lucy”."]'),
('film-joaquin-phoenix', 'Joaquin Phoenix', 'film', 'aktor', '["Zdobył Oscara za „Joker”.","Wystąpił w „Her”.","Zagrał w „Gladiator”."]'),
('film-keanu-reeves', 'Keanu Reeves', 'film', 'aktor', '["Zagrał Neo w „Matrix”.","Wystąpił w serii „John Wick”.","Znany z filmu „Speed”."]'),
('film-robert-downey-jr', 'Robert Downey Jr.', 'film', 'aktor', '["Zagrał Iron Mana w MCU.","Wystąpił w „Sherlock Holmes”.","Znany z roli w „Chaplin”."]'),
('film-harrison-ford', 'Harrison Ford', 'film', 'aktor', '["Zagrał Hana Solo.","Wystąpił jako Indiana Jones.","Znany z „Blade Runner”."]'),
('film-sigourney-weaver', 'Sigourney Weaver', 'film', 'aktorka', '["Zagrała Ripley w „Obcy”.","Wystąpiła w „Avatar”.","Ikona kina science‑fiction."]'),
('film-samuel-l-jackson', 'Samuel L. Jackson', 'film', 'aktor', '["Zagrał w „Pulp Fiction”.","Wystąpił jako Nick Fury.","Często gra w filmach Tarantino."]'),
('film-charlize-theron', 'Charlize Theron', 'film', 'aktorka', '["Zdobyła Oscara za „Monster”.","Wystąpiła w „Mad Max: Na drodze gniewu”.","Pochodzi z RPA."]'),
('film-hugh-jackman', 'Hugh Jackman', 'film', 'aktor', '["Zagrał Wolverine.","Wystąpił w „Les Misérables”.","Znany z „The Greatest Showman”."]'),
('film-christian-bale', 'Christian Bale', 'film', 'aktor', '["Zagrał Batmana u Nolana.","Znany z „American Psycho”.","Zdobył Oscara za „The Fighter”."]'),
('film-emma-stone', 'Emma Stone', 'film', 'aktorka', '["Zdobyła Oscara za „La La Land”.","Wystąpiła w „The Help”.","Zagrała w „Cruella”."]'),
('film-ryan-gosling', 'Ryan Gosling', 'film', 'aktor', '["Zagrał w „La La Land”.","Wystąpił w „Drive”.","Znany z „Blade Runner 2049”."]'),
-- Muzyka (30)
('music-madonna', 'Madonna', 'muzyka', 'piosenkarka', '["Nazywana „Królową Popu”.","Zasłynęła w latach 80.","Ma utwór „Like a Virgin”."]'),
('music-michael-jackson', 'Michael Jackson', 'muzyka', 'piosenkarz', '["Nazywany „Królem Popu”.","Wydał album „Thriller”.","Słynął z moonwalk."]'),
('music-queen-mercury', 'Freddie Mercury', 'muzyka', 'wokalista', '["Był liderem zespołu Queen.","Śpiewał „Bohemian Rhapsody”.","Urodził się jako Farrokh Bulsara."]'),
('music-elvis', 'Elvis Presley', 'muzyka', 'piosenkarz', '["Nazywany „Królem Rock and Rolla”.","Pochodził z USA.","Zagrał w wielu filmach muzycznych."]'),
('music-bowie', 'David Bowie', 'muzyka', 'piosenkarz', '["Znany z artystycznych metamorfoz.","Stworzył postać Ziggy Stardust.","Ma utwór „Heroes”."]'),
('music-adele', 'Adele', 'muzyka', 'piosenkarka', '["Brytyjska wokalistka.","Album „21” przyniósł jej Grammy.","Znana z ballad."]'),
('music-beyonce', 'Beyoncé', 'muzyka', 'piosenkarka', '["Była w zespole Destiny’s Child.","Ma album „Lemonade”.","Występuje w stylu R&B i pop."]'),
('music-rihanna', 'Rihanna', 'muzyka', 'piosenkarka', '["Pochodzi z Barbadosu.","Ma utwór „Umbrella”.","Łączy pop i R&B."]'),
('music-taylor-swift', 'Taylor Swift', 'muzyka', 'piosenkarka', '["Zaczynała w muzyce country.","Album „1989” to popowy przełom.","Znana z autorskich tekstów."]'),
('music-ed-sheeran', 'Ed Sheeran', 'muzyka', 'piosenkarz', '["Brytyjski artysta.","Ma utwór „Shape of You”.","Gra na gitarze akustycznej."]'),
('music-lady-gaga', 'Lady Gaga', 'muzyka', 'piosenkarka', '["Znana z ekstrawaganckiego stylu.","Ma utwór „Poker Face”.","Wystąpiła w filmie „A Star Is Born”."]'),
('music-bob-dylan', 'Bob Dylan', 'muzyka', 'piosenkarz', '["Laureat literackiego Nobla.","Ikona folku i rocka.","Napisał „Like a Rolling Stone”."]'),
('music-bruce-springsteen', 'Bruce Springsteen', 'muzyka', 'piosenkarz', '["Nazywany „The Boss”.","Album „Born in the U.S.A.”.","Znany z rockowych hymnów."]'),
('music-prince', 'Prince', 'muzyka', 'piosenkarz', '["Wieloinstrumentalista.","Album „Purple Rain”.","Łączył funk i pop."]'),
('music-whitney', 'Whitney Houston', 'muzyka', 'piosenkarka', '["Znana z potężnego głosu.","Śpiewała „I Will Always Love You”.","Była gwiazdą lat 80. i 90."]'),
('music-aretha', 'Aretha Franklin', 'muzyka', 'piosenkarka', '["Nazywana „Królową Soulu”.","Wykonywała utwór „Respect”.","Ikona muzyki soul."]'),
('music-kanye', 'Kanye West', 'muzyka', 'raper', '["Producent i raper.","Album „The College Dropout”.","Znany z kontrowersji medialnych."]'),
('music-eminem', 'Eminem', 'muzyka', 'raper', '["Wykonawca „Lose Yourself”.","Zdobył Oscary i Grammy.","Znany z szybkiego flow."]'),
('music-drake', 'Drake', 'muzyka', 'raper', '["Kanadyjski artysta.","Łączy rap i R&B.","Ma hit „God’s Plan”."]'),
('music-billie-eilish', 'Billie Eilish', 'muzyka', 'piosenkarka', '["Zasłynęła w młodym wieku.","Album „When We All Fall Asleep…”.","Znana z mrocznego brzmienia."]'),
('music-coldplay', 'Chris Martin', 'muzyka', 'piosenkarz', '["Lider zespołu Coldplay.","Wykonawca „Viva la Vida”.","Pochodzi z Wielkiej Brytanii."]'),
('music-shakira', 'Shakira', 'muzyka', 'piosenkarka', '["Pochodzi z Kolumbii.","Ma utwór „Hips Don’t Lie”.","Łączy pop i latynoskie brzmienia."]'),
('music-justin-bieber', 'Justin Bieber', 'muzyka', 'piosenkarz', '["Zaczynał karierę w YouTube.","Ma hit „Baby”.","Kanadyjski artysta pop."]'),
('music-bruno-mars', 'Bruno Mars', 'muzyka', 'piosenkarz', '["Wykonawca „Uptown Funk”.","Łączy pop, funk i soul.","Zdobywca Grammy."]'),
('music-dua-lipa', 'Dua Lipa', 'muzyka', 'piosenkarka', '["Brytyjska wokalistka.","Album „Future Nostalgia”.","Ma hit „Don’t Start Now”."]'),
('music-kendrick', 'Kendrick Lamar', 'muzyka', 'raper', '["Album „To Pimp a Butterfly”.","Laureat Pulitzera.","Znany z tekstów społecznych."]'),
('music-weeknd', 'The Weeknd', 'muzyka', 'piosenkarz', '["Wykonawca „Blinding Lights”.","Kanadyjski artysta R&B.","Znany z charakterystycznego falsetu."]'),
('music-amy-winehouse', 'Amy Winehouse', 'muzyka', 'piosenkarka', '["Album „Back to Black”.","Znana z soulowego brzmienia.","Brytyjska artystka."]'),
('music-freddie-gibbs', 'Freddie Gibbs', 'muzyka', 'raper', '["Amerykański raper.","Znany z albumów z The Alchemist.","Tworzy rap uliczny."]'),
('music-sia', 'Sia', 'muzyka', 'piosenkarka', '["Australijska artystka.","Znana z utworu „Chandelier”.","Często ukrywa wizerunek."]'),
-- Nauka (30)
('science-einstein', 'Albert Einstein', 'nauka', 'fizyk teoretyczny', '["Sformułował szczególną teorię względności.","Otrzymał Nobla za fotoefekt.","Urodził się w Ulm."]'),
('science-curie', 'Maria Skłodowska-Curie', 'nauka', 'fizyczka i chemiczka', '["Odkryła polon i rad.","Pracowała w Paryżu.","Dwa Noble w naukach ścisłych."]'),
('science-newton', 'Isaac Newton', 'nauka', 'fizyk i matematyk', '["Sformułował prawo grawitacji.","Autor „Principia Mathematica”.","Żył w XVII wieku."]'),
('science-tesla', 'Nikola Tesla', 'nauka', 'wynalazca', '["Pracował nad prądem przemiennym.","Stworzył cewkę Tesli.","Pochodził z terenów dzisiejszej Chorwacji."]'),
('science-darwin', 'Charles Darwin', 'nauka', 'przyrodnik', '["Autor teorii ewolucji.","Podróżował na HMS Beagle.","Napisał „O powstawaniu gatunków”."]'),
('science-galilei', 'Galileo Galilei', 'nauka', 'astronom', '["Udoskonalił teleskop.","Popierał heliocentryzm.","Odkrył księżyce Jowisza."]'),
('science-kepler', 'Johannes Kepler', 'nauka', 'astronom', '["Sformułował prawa ruchu planet.","Współpracował z Brahe.","Żył na przełomie XVI i XVII w."]'),
('science-copernicus', 'Mikołaj Kopernik', 'nauka', 'astronom', '["Twórca teorii heliocentrycznej.","Autor „De revolutionibus”.","Pochodził z Torunia."]'),
('science-hawking', 'Stephen Hawking', 'nauka', 'kosmolog', '["Badał czarne dziury.","Autor „Krótka historia czasu”.","Pracował w Cambridge."]'),
('science-feynman', 'Richard Feynman', 'nauka', 'fizyk', '["Noblista za elektrodynamikę kwantową.","Uczestnik Projektu Manhattan.","Znany z Feynman Lectures."]'),
('science-bohr', 'Niels Bohr', 'nauka', 'fizyk', '["Twórca modelu atomu.","Noblista w dziedzinie fizyki.","Działał w Kopenhadze."]'),
('science-planck', 'Max Planck', 'nauka', 'fizyk', '["Wprowadził stałą Plancka.","Ojciec mechaniki kwantowej.","Noblista 1918."]'),
('science-heisenberg', 'Werner Heisenberg', 'nauka', 'fizyk', '["Zasada nieoznaczoności.","Laureat Nobla.","Niemiecki fizyk."]'),
('science-schrodinger', 'Erwin Schrödinger', 'nauka', 'fizyk', '["Równanie Schrödingera.","Słynny eksperyment z kotem.","Wkład w mechanikę kwantową."]'),
('science-wozniak', 'Steve Wozniak', 'nauka', 'inżynier', '["Współzałożyciel Apple.","Projektował wczesne komputery Apple.","Inżynier elektronik."]'),
('science-turing', 'Alan Turing', 'nauka', 'matematyk', '["Złamał szyfr Enigmy.","Twórca maszyny Turinga.","Ojciec informatyki."]'),
('science-lovelace', 'Ada Lovelace', 'nauka', 'matematyczka', '["Opisała algorytm dla maszyny analitycznej.","Uważana za pierwszą programistkę.","Żyła w XIX wieku."]'),
('science-crick', 'Francis Crick', 'nauka', 'biolog', '["Współodkrywca struktury DNA.","Noblista 1962.","Pracował w Cambridge."]'),
('science-watson', 'James Watson', 'nauka', 'biolog', '["Współodkrywca DNA.","Noblista 1962.","Amerykański naukowiec."]'),
('science-gould', 'Jane Goodall', 'nauka', 'prymatolożka', '["Badała szympansy w Tanzanii.","Działaczka ekologiczna.","Autorka wielu książek."]'),
('science-sagan', 'Carl Sagan', 'nauka', 'astronom', '["Popularyzator nauki.","Autor „Cosmos”.","Współtwórca misji Voyager."]'),
('science-tyson', 'Neil deGrasse Tyson', 'nauka', 'astrofizyk', '["Popularyzator astronomii.","Prowadził „Cosmos”.","Dyrektor Hayden Planetarium."]'),
('science-ferm', 'Enrico Fermi', 'nauka', 'fizyk', '["Pracował nad reaktorem jądrowym.","Laureat Nobla.","Włosko‑amerykański uczony."]'),
('science-pasteur', 'Louis Pasteur', 'nauka', 'chemik', '["Twórca pasteryzacji.","Badacz drobnoustrojów.","Wkład w szczepionki."]'),
('science-euler', 'Leonhard Euler', 'nauka', 'matematyk', '["Wkład w analizę i teorię liczb.","Wprowadził oznaczenie funkcji f(x).","Szwajcarski uczony."]'),
('science-gauss', 'Carl Friedrich Gauss', 'nauka', 'matematyk', '["„Książę matematyków”.","Wkład w geometrię i statystykę.","Niemiecki uczony."]'),
('science-faraday', 'Michael Faraday', 'nauka', 'fizyk', '["Odkrył indukcję elektromagnetyczną.","Pionier elektrotechniki.","Autodidakta."]'),
('science-raman', 'C. V. Raman', 'nauka', 'fizyk', '["Odkrył efekt Ramana.","Noblista 1930.","Indyjski fizyk."]'),
('science-meitner', 'Lise Meitner', 'nauka', 'fizyczka', '["Współodkryła rozszczepienie jądra.","Pracowała w Berlinie i Szwecji.","Austriacko‑szwedzka uczona."]'),
('science-herschel', 'Caroline Herschel', 'nauka', 'astronomka', '["Odkrywała komety.","Współpracowała z Williamem Herschelem.","Pionierka astronomii."]'),
-- Polska (30)
('pl-copernicus', 'Mikołaj Kopernik', 'polska', 'astronom', '["Twórca teorii heliocentrycznej.","Autor „De revolutionibus”.","Urodził się w Toruniu."]'),
('pl-curie', 'Maria Skłodowska-Curie', 'polska', 'naukowczyni', '["Urodziła się w Warszawie.","Odkryła polon i rad.","Dwa Noble w naukach ścisłych."]'),
('pl-szymborska', 'Wisława Szymborska', 'polska', 'poetka', '["Laureatka Nobla w literaturze.","Autorka „Koniec i początek”.","Związana z Krakowem."]'),
('pl-milosz', 'Czesław Miłosz', 'polska', 'poeta', '["Nobel w literaturze 1980.","Autor „Zniewolony umysł”.","Urodził się w Szetejniach."]'),
('pl-lem', 'Stanisław Lem', 'polska', 'pisarz', '["Autor „Solaris”.","Pisarz science‑fiction.","Urodził się we Lwowie."]'),
('pl-sienkiewicz', 'Henryk Sienkiewicz', 'polska', 'pisarz', '["Nobel w literaturze 1905.","Autor „Quo Vadis”.","Napisał „Trylogię”."]'),
('pl-chopin', 'Fryderyk Chopin', 'polska', 'kompozytor', '["Urodził się w Żelazowej Woli.","Komponował na fortepian.","Związany z Paryżem."]'),
('pl-mickiewicz', 'Adam Mickiewicz', 'polska', 'poeta', '["Autor „Pan Tadeusz”.","Wieszcz narodowy.","Urodził się w 1798 roku."]'),
('pl-kosciuszko', 'Tadeusz Kościuszko', 'polska', 'dowódca', '["Bohater insurekcji 1794.","Brał udział w wojnie o niepodległość USA.","Urodził się na Polesiu."]'),
('pl-pilsudski', 'Józef Piłsudski', 'polska', 'polityk', '["Marszałek Polski.","Współtwórca niepodległej Polski.","Żył w latach 1867–1935."]'),
('pl-walesa', 'Lech Wałęsa', 'polska', 'działacz', '["Lider Solidarności.","Nobel pokojowy 1983.","Prezydent RP w latach 90."]'),
('pl-jan-pawel-ii', 'Jan Paweł II', 'polska', 'papież', '["Papież w latach 1978–2005.","Urodził się w Wadowicach.","Pierwszy papież z Polski."]'),
('pl-zygmunt', 'Zygmunt Bauman', 'polska', 'socjolog', '["Autor pojęcia „płynnej nowoczesności”.","Profesor socjologii.","Urodził się w Poznaniu."]'),
('pl-kieslowski', 'Krzysztof Kieślowski', 'polska', 'reżyser', '["Autor „Dekalogu”.","Stworzył trylogię „Trzy kolory”.","Wybitny polski reżyser."]'),
('pl-wajda', 'Andrzej Wajda', 'polska', 'reżyser', '["Wyreżyserował „Człowiek z marmuru”.","Laureat Oscara honorowego.","Autor „Kanału”."]'),
('pl-penderecki', 'Krzysztof Penderecki', 'polska', 'kompozytor', '["Wybitny kompozytor współczesny.","Autor „Trenu Ofiarom Hiroszimy”.","Urodził się w Dębicy."]'),
('pl-szymanowski', 'Karol Szymanowski', 'polska', 'kompozytor', '["Autor „Harnasie”.","Polski kompozytor XX wieku.","Związany z Zakopanem."]'),
('pl-herbert', 'Zbigniew Herbert', 'polska', 'poeta', '["Autor „Pan Cogito”.","Poeta XX wieku.","Urodził się we Lwowie."]'),
('pl-tuwim', 'Julian Tuwim', 'polska', 'poeta', '["Autor „Lokomotywa”.","Poeta Skamandra.","Urodził się w Łodzi."]'),
('pl-prus', 'Bolesław Prus', 'polska', 'pisarz', '["Autor „Lalka”.","Pozytywista.","Urodził się w 1847 roku."]'),
('pl-ociepa', 'Olga Tokarczuk', 'polska', 'pisarka', '["Laureatka Nobla 2018.","Autorka „Bieguni”.","Mieszka na Dolnym Śląsku."]'),
('pl-mazowiecki', 'Tadeusz Mazowiecki', 'polska', 'polityk', '["Pierwszy niekomunistyczny premier po 1989.","Działacz opozycji.","Urodził się w 1927 roku."]'),
('pl-kazimierz', 'Kazimierz Wielki', 'polska', 'król', '["Panował w XIV wieku.","Ostatni król z dynastii Piastów.","Rozbudował system prawa."]'),
('pl-sobieski', 'Jan III Sobieski', 'polska', 'król', '["Zwycięzca spod Wiednia 1683.","Król Polski.","Znany z odsieczy wiedeńskiej."]'),
('pl-zawadzki', 'Irena Sendlerowa', 'polska', 'działaczka', '["Ratowała dzieci z getta warszawskiego.","Działaczka społeczna.","Uhonorowana po wojnie."]'),
('pl-skodowska', 'Władysław Reymont', 'polska', 'pisarz', '["Nobel w literaturze 1924.","Autor „Chłopi”.","Urodził się w Kobielach."]'),
('pl-agnieszka', 'Agnieszka Holland', 'polska', 'reżyserka', '["Polska reżyserka filmowa.","Wyreżyserowała „Europa Europa”.","Pracuje także w USA."]'),
('pl-grotowski', 'Jerzy Grotowski', 'polska', 'reżyser', '["Reżyser teatralny.","Twórca „teatru ubogiego”.","Związany z Wrocławiem."]'),
('pl-kozminski', 'Tadeusz Kotarbiński', 'polska', 'filozof', '["Przedstawiciel szkoły lwowsko‑warszawskiej.","Twórca prakseologii.","Urodził się w 1886 roku."]'),
('pl-sklodowska', 'Hanna Krall', 'polska', 'pisarka', '["Autorka „Zdążyć przed Panem Bogiem”.","Dziennikarka i pisarka.","Urodziła się w Warszawie."]'),
-- Testowa (30, realne osoby)
('testowa-einstein', 'Albert Einstein', 'testowa', 'fizyk teoretyczny', '["Sformułował teorię względności.","Noblista za fotoefekt.","Urodził się w Ulm."]'),
('testowa-curie', 'Maria Skłodowska-Curie', 'testowa', 'fizyczka i chemiczka', '["Odkryła polon i rad.","Pracowała w Paryżu.","Dwa Noble w naukach ścisłych."]'),
('testowa-jobs', 'Steve Jobs', 'testowa', 'przedsiębiorca', '["Współzałożyciel Apple.","Wprowadził iPhone.","Był wizjonerem branży tech."]'),
('testowa-king', 'Stephen King', 'testowa', 'pisarz', '["Autor „To”.","Pisze horrory.","Nazywany królem grozy."]'),
('testowa-rowling', 'J.K. Rowling', 'testowa', 'pisarka', '["Autorka „Harry Potter”.","Brytyjska pisarka.","Zaczęła pisać w kawiarniach."]'),
('testowa-madonna', 'Madonna', 'testowa', 'piosenkarka', '["Nazywana Królową Popu.","Znana od lat 80.","Ma utwór „Vogue”."]'),
('testowa-hawking', 'Stephen Hawking', 'testowa', 'kosmolog', '["Badał czarne dziury.","Autor „Krótka historia czasu”.","Pracował w Cambridge."]'),
('testowa-mercury', 'Freddie Mercury', 'testowa', 'wokalista', '["Lider Queen.","Śpiewał „Bohemian Rhapsody”.","Urodził się jako Farrokh Bulsara."]'),
('testowa-tarantino', 'Quentin Tarantino', 'testowa', 'reżyser', '["Wyreżyserował „Pulp Fiction”.","Znany z dialogów i przemocy.","Stoi za „Kill Bill”."]'),
('testowa-de-niro', 'Robert De Niro', 'testowa', 'aktor', '["Współpracował ze Scorsese.","Zagrał w „Taksówkarz”.","Znany z „You talkin'' to me?”."]'),
('testowa-newton', 'Isaac Newton', 'testowa', 'fizyk', '["Prawo grawitacji.","Autor „Principia”.","Uczony XVII wieku."]'),
('testowa-tesla', 'Nikola Tesla', 'testowa', 'wynalazca', '["Prąd przemienny.","Cewka Tesli.","Wynalazca z przełomu wieków."]'),
('testowa-darwin', 'Charles Darwin', 'testowa', 'przyrodnik', '["Teoria ewolucji.","HMS Beagle.","Autor „O powstawaniu gatunków”."]'),
('testowa-galilei', 'Galileo Galilei', 'testowa', 'astronom', '["Udoskonalił teleskop.","Popierał heliocentryzm.","Odkrył księżyce Jowisza."]'),
('testowa-chopin', 'Fryderyk Chopin', 'testowa', 'kompozytor', '["Urodził się w Żelazowej Woli.","Komponował na fortepian.","Związany z Paryżem."]'),
('testowa-beethoven', 'Ludwig van Beethoven', 'testowa', 'kompozytor', '["Mimo głuchoty tworzył muzykę.","Autor IX Symfonii.","Niemiecki kompozytor."]'),
('testowa-vangogh', 'Vincent van Gogh', 'testowa', 'malarz', '["Autor „Gwiaździsta noc”.","Postimpresjonista.","Pochodził z Holandii."]'),
('testowa-picasso', 'Pablo Picasso', 'testowa', 'malarz', '["Współtwórca kubizmu.","Autor „Guernica”.","Urodził się w Hiszpanii."]'),
('testowa-da-vinci', 'Leonardo da Vinci', 'testowa', 'malarz', '["Autor „Mona Lisa”.","Genialny wynalazca renesansu.","Namaloował „Ostatnią Wieczerzę”."]'),
('testowa-shakespeare', 'William Shakespeare', 'testowa', 'dramaturg', '["Autor „Hamlet”.","Tworzył w epoce elżbietańskiej.","Znany jako Bard z Avon."]'),
('testowa-mandela', 'Nelson Mandela', 'testowa', 'polityk', '["Walczył z apartheidem.","Prezydent RPA.","Nobel pokojowy."]'),
('testowa-churchill', 'Winston Churchill', 'testowa', 'polityk', '["Premier Wielkiej Brytanii w II WŚ.","Słynny mówca.","Laureat Nobla w literaturze."]'),
('testowa-earhart', 'Amelia Earhart', 'testowa', 'pilotka', '["Pierwsza kobieta nad Atlantykiem.","Zaginęła w 1937 roku.","Ikona lotnictwa."]'),
('testowa-kahlo', 'Frida Kahlo', 'testowa', 'malarka', '["Meksykańska artystka.","Tworzyła autoportrety.","Związana z Diego Riverą."]'),
('testowa-chaplin', 'Charlie Chaplin', 'testowa', 'aktor', '["Gwiazda kina niemego.","Postać włóczęgi.","Autor filmu „Dyktator”."]'),
('testowa-jordan', 'Michael Jordan', 'testowa', 'koszykarz', '["Gwiazda NBA.","Numer 23.","Sześciokrotny mistrz."]'),
('testowa-serena', 'Serena Williams', 'testowa', 'tenisistka', '["Wielkoszlemowa mistrzyni.","Zdominowała tenis kobiet.","Pochodzi z USA."]'),
('testowa-anne-frank', 'Anne Frank', 'testowa', 'autorka dziennika', '["Pisała dziennik w ukryciu.","Żyła w Amsterdamie.","Symbol II wojny światowej."]'),
('testowa-lovelace', 'Ada Lovelace', 'testowa', 'matematyczka', '["Uważana za pierwszą programistkę.","Współpracowała z Babbage''em.","Żyła w XIX wieku."]'),
('testowa-turing', 'Alan Turing', 'testowa', 'matematyk', '["Złamał Enigmę.","Twórca maszyny Turinga.","Ojciec informatyki."]');
